### ISSUE TITLE
scan qr code can not get the proper result

### ISSUE THREAD

**Issue by wangqi060934** [fate-lovely/alfred-qrcode-workflow#1]
Just like this url:
http://openbox.mobilem.360.cn/qcms/view/t/detail?sid=104391&has_oem=1&marketid=10000001&ref=thirdlink&appver=2.0.0.1485&m=91822b9eb7c581e0208aec3be094eec&f=sjzsweb
Generate qr code is ok, but when I want to scan the qr code it only returns "http://openbox.mobilem."

**Comment by cj1128** [comment]
This is the problem of the parsing library I used. I need to replace this one, however, currently I can't find a good Go library to do this job.

I am thinking invoking a C library in Go, but I haven't done that before, so this may take some time to finish.

**Comment by cj1128** [comment]
@wangqi060934 Hi, I reimplement the parsing function using `zbar`, and it seems to work well 😄
Just download the latest workflow and give it a try.
I am closing this issue now, if you have any problem, don't hesitate to give a feedback, thank you.
