### ISSUE TITLE
Can change the folder where the QR code is created from Private/Tmp to somewhere else?

### ISSUE THREAD

**Issue by itoldusoandso** [fate-lovely/alfred-qrcode-workflow#4]
Hello, 
Is there a way to set the directory where the qr code image is saved? 
I see it is by default saved into Private/Tmp folder. 
I would like it to be in my Downloads folder.
Thank you

**Comment by cj1128** [comment]
@itoldusoandso Hi, you can install the latest version and it supports setting qr code dir. 

<img width="1200" alt="image" src="https://github.com/cj1128/alfred-qrcode-workflow/assets/4210829/e01153b0-5e6b-46a3-bfc6-156da9a1b49f">

**Comment by itoldusoandso** [comment]
Thank you. Good now.
